### ISSUE TITLE
이거 접속

### ISSUE THREAD

**Issue by sungho0205** [thoratica/blow.ga#1]
접속이 안되는데 뭔가요?

**Comment by sorulove** [comment]
그거 띠까님이 헤로쿠나 AWS로 호스팅 한게 아니라 개인 컴퓨터 IP로 포트포워딩 해서 열어서 그런거 같습니다. 개인 IP로 포트포워딩 하면 컴퓨터를 계속 켜야하는데, 컴퓨터를 껐거나, 서버를 잠시 껐을 수도 있습니다. 또는 다른 이유로 접속이 안 될 수도 있겠죠 :)

**Comment by thoratica** [comment]
이 레포는 blow.ga랑 별개입니다. 접속 문제는 이슈가 아닌 다른 연락 수단으로 알려주세요.
접속이 안되는건 해킹범 때문에 일시적으로 제가 서버를 내려서 그런거고, 방금 전에 다시 올렸습니다.
