### ISSUE TITLE
혹시 저도 쓸수 있을까요

### ISSUE THREAD

**Issue by injoon5** [thoratica/blow.ga#2]
저도 단축기를 만들고 싶은데 
혹시 저도 쓸 수 있을까요?
그리고 작동 원리를 알려주실 수 있으시다면 감사하겠습니다.

**Comment by thoratica** [comment]
쓰라고 소스 공개한겁니다 ㅎㅎ
원리는 대충 db에 번호 (또는 커스텀 링크) 랑 대상 링크를 같이 저장해두고 저장된 번호로 접속하면 대상 링크로 리다이렉트 시켜주는거지만 제가 너무 못 알아듣게 설명한 거 같네요...

**Comment by thoratica** [comment]
코드가 스파게티라서 직접 구현하시는기 나을겁니다... ㅠㅠ
