### ISSUE TITLE
혹시 설치 시 필요한것들을 알려 주실 수 있으실까요?

### ISSUE THREAD

**Issue by injoon5** [thoratica/blow.ga#3]
혹시 설치 시 필요한것들을 알려 주실 수 있으실까요?(node.js/mongodb 등)
그리고 설치시 필요한 명령어가 있을까요

**Comment by thoratica** [comment]
node.js 설치하셨으면 다운로드 받은 디렉토리로 이동해서
`npm install`
한 번 돌려주시면 바로 설치됩니다.
