### ISSUE TITLE
혹시 이거 호스팅은 뭘 쓰나요?

### ISSUE THREAD

**Issue by injoon5** [thoratica/blow.ga#4]
계속 귀찮게 해서 죄송합니다.
제가 이걸 컴퓨터가 아닌 heroku에 설치해봤는데, 혹시 @thoratica 님이 쓰시는 호스팅이 있을까요?
(단어가 잘 생각 안나서 호스팅이라고 일단 써놨습니다.)

**Comment by thoratica** [comment]
전 AWS 프리 히어로 돌리고 있습니다.

**Comment by injoon5** [comment]
제가 오늘 돌아다니다 [glitch] (https://glitch.com) 이라는 곳을 발견 했는데, 꽤 좋습니다. 프리 티어 끝나면 여기서 돌리세요!!
